// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFGWao6K1k6oeHUF7fW3xe9ZjhFB7BGT8',
    appId: '1:711100586756:web:ea61c0d766c82e8bb10e51',
    messagingSenderId: '711100586756',
    projectId: 'safe-zone-app-2b185',
    authDomain: 'safe-zone-app-2b185.firebaseapp.com',
    storageBucket: 'safe-zone-app-2b185.firebasestorage.app',
    measurementId: 'G-J5TPWP1L3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6TCnScWunBhwKcsH_Xmy228P8qmk7NCY',
    appId: '1:711100586756:android:44ff565bff6e7950b10e51',
    messagingSenderId: '711100586756',
    projectId: 'safe-zone-app-2b185',
    storageBucket: 'safe-zone-app-2b185.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYHv3S0nF-A4z_JPp1rYMOW5ANv_u9mPE',
    appId: '1:711100586756:ios:f6a60851a4eb7aecb10e51',
    messagingSenderId: '711100586756',
    projectId: 'safe-zone-app-2b185',
    storageBucket: 'safe-zone-app-2b185.firebasestorage.app',
    iosBundleId: 'com.example.safezone.safeZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYHv3S0nF-A4z_JPp1rYMOW5ANv_u9mPE',
    appId: '1:711100586756:ios:f6a60851a4eb7aecb10e51',
    messagingSenderId: '711100586756',
    projectId: 'safe-zone-app-2b185',
    storageBucket: 'safe-zone-app-2b185.firebasestorage.app',
    iosBundleId: 'com.example.safezone.safeZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFGWao6K1k6oeHUF7fW3xe9ZjhFB7BGT8',
    appId: '1:711100586756:web:8d2f476eec707e9bb10e51',
    messagingSenderId: '711100586756',
    projectId: 'safe-zone-app-2b185',
    authDomain: 'safe-zone-app-2b185.firebaseapp.com',
    storageBucket: 'safe-zone-app-2b185.firebasestorage.app',
    measurementId: 'G-6R8KTJZMLE',
  );
}
